_commit: v1.12.1-7-g14d754f
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: 'app: flaresolverr'
name: flaresolverr
namespace: flaresolverr
pvc: false
reloader: false
resources:
- deployments.yaml
- pvcs.yaml
- services.yaml
- service-accounts.yaml
service: false
serviceAccount: false
upstreamURL: https://github.com/FlareSolverr/FlareSolverr
url: https://github.com/charlesthomas/homelab-flaresolverr
