---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flaresolverr

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-flaresolverr
commonLabels:
  app: flaresolverr

resources:
- resources/deployments.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/services.yaml
- resources/service-accounts.yaml
