---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaresolverr-config
  namespace: flaresolverr
  labels:
    app.kubernetes.io/instance: flaresolverr
    app.kubernetes.io/name: flaresolverr
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
