---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: flaresolverr
  labels:
    app.kubernetes.io/instance: flaresolverr
    app.kubernetes.io/name: flaresolverr
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 8191
      protocol: TCP
      targetPort: 8191
  selector:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/instance: flaresolverr
